Repository MON-DA-Y/FE, pull requests merged in 2025-07, with the labels that each got.

#19 Feat/#18/학생 마이페이지
  public/icons/Edit_Image.svg
  src/app/user/components/AttendBtn.tsx
  src/app/user/components/Slider.tsx
  src/app/user/parent/[studentId]/page.tsx
  src/app/user/parent/mypage/page.tsx
  src/app/user/student/components/ProfileImage.tsx
  src/app/user/student/components/StudentEdit.tsx
  src/app/user/student/page.tsx
Labels: ✨ Feature, 💰 혜원

#25 Feat/#24/mon word
  public/icons/MonWord_header.svg
  public/icons/next.svg
  src/app/(main)/MonWord/components/WordItem.tsx
  src/app/(main)/MonWord/components/WordList.tsx
  src/app/(main)/MonWord/page.tsx
  src/app/(main)/student/components/MonNews.tsx
  src/app/(main)/student/components/MonQuiz.tsx
  src/app/(main)/student/components/TodayLearningRate.tsx
  src/components/shared/CommonBtn.tsx
  src/components/shared/HomeBtn.tsx
  src/components/ui/NavyBox.tsx
Labels: ✨ Feature, 💰 동은, 🎨 Design

#29 Feat/#28/MonQuiz 구현
  public/icons/MonQuiz_header.svg
  src/app/(main)/MonNews/components/NewsItem.tsx
  src/app/(main)/MonQuiz/components/QuizItem.tsx
  src/app/(main)/MonQuiz/components/QuizList.tsx
  src/app/(main)/MonQuiz/components/QuizMarkItem.tsx
  src/app/(main)/MonQuiz/components/QuizMarkList.tsx
  src/app/(main)/MonQuiz/page.tsx
  src/app/(main)/MonWord/components/WordList.tsx
  src/components/shared/CommonBtn.tsx
  src/components/ui/Choice.tsx
  src/components/ui/RedBox.tsx
Labels: ✨ Feature, 💰 동은

#31 Feat/#30/MonSeries
  public/icons/MonSeries_header.svg
  public/icons/Pin_LearnedPart.svg
  public/icons/Pin_UpcomingPart.svg
  public/icons/Series_blue.svg
  public/icons/Series_yellow.svg
  src/app/(main)/MonSeries/components/ViewSwitchTab.tsx
  src/app/(main)/MonSeries/components/keyword/KeywordItem.tsx
  src/app/(main)/MonSeries/components/keyword/KeywordList.tsx
  src/app/(main)/MonSeries/components/keyword/SelectSeries.tsx
  src/app/(main)/MonSeries/components/keyword/SeriesSelectModal.tsx
  src/app/(main)/MonSeries/components/series/PartItem.tsx
  src/app/(main)/MonSeries/components/series/SeriesItem.tsx
  src/app/(main)/MonSeries/components/series/SeriesList.tsx
  src/app/(main)/MonSeries/page.tsx
  src/styles/theme/tokens.ts
Labels: ✨ Feature, 💰 동은
