Repository MON-DA-Y/FE, pull requests merged in 2025-05, with the labels that each got.

#2 Setting: prettier 설정
  .prettierrc
Labels: 💰 동은, ⚙️ Setting

#4 1 setting 깃허브 초기 세팅
  app/globals.css
  app/layout.tsx
  app/page.tsx
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/icons/favicon.ico
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/(auth)/layout.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/styles/globals.css
  src/styles/theme/tokens.ts
  tailwind.config.ts
  tsconfig.json
Labels: 💰 동은, ⚙️ Setting

#5 1 setting 깃허브 초기 세팅 - Tailwind CSS 설정
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/globals.css
  src/app/layout.tsx
Labels: 🐞 Fix, 💰 동은, ⚙️ Setting

#7 Feat/#3/account UI
  .prettierrc
  package-lock.json
  package.json
  public/images/logo.svg
  public/images/parent.png
  public/images/polygon_mint.svg
  public/images/polygon_navy.svg
  public/images/student.png
  src/app/account/components/Input.tsx
  src/app/account/components/MessageBox.tsx
  src/app/account/components/icon.tsx
  src/app/account/layout.tsx
  src/app/account/login/page.tsx
  src/app/account/page.tsx
  src/app/account/signup/components/SignUpBtn.tsx
  src/app/account/signup/components/SignUpForm.tsx
  src/app/account/signup/parent/page.tsx
  src/app/account/signup/student/page.tsx
  src/app/account/signupsuccess/parent/page.tsx
  src/app/account/signupsuccess/student/page.tsx
  src/app/globals.css
  src/app/page.tsx
Labels: ✨ Feature, 💰 혜원

#11 Setting/#1 : pull request, issue 템플릿 설정, 폰트 설정 / PC, 모바일 뷰 설정
  .github/ISSUE_TEMPLATE/monday_issue.md
  .github/pull_request_template.md
  src/app/globals.css
Labels: 💰 동은, ⚙️ Setting

#12 Revert "Setting/#1 : pull request, issue 템플릿 설정, 폰트 설정 / PC, 모바일 뷰 설정"
  .github/ISSUE_TEMPLATE/monday_issue.md
  .github/pull_request_template.md
  src/app/globals.css
Labels: 🐞 Fix
